os: linux
group: stable
dist: trusty
sudo: required
language: node_js
node_js: 8

branches:
  only: master

before_script:
  - npm install -g istanbul codecov

script:
  - npm run codecov

notifications:
  email: bianco@javanile.org
